import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ModalProvider } from "@/components/modal.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI_SASS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ModalProvider />
          {children} {/* This renders the page's content */}
        </body>
      </html>
    </ClerkProvider>
  );
}
